import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HearoSection from "@/component/hero-section/HearoSection";
import Section2 from "@/component/section2/Section2";


const Home = () => {

  const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 3000 },
      items: 12
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 2
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 8
    }
  };

  return (
    <>
      <Head>
        <title>IMDb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HearoSection/>
        <Section2/>

      </main>
    </>
  );
}


export default Home
